# Controller settings 
optitrack:
  body_part_names: ["neck_link2", "trunk_rz", "hip_base", "LL_foot", "RL_foot", "la_end_effector", "ra_end_effector", "la_link4", "ra_link4"]
  indices: [5, 3, 2, 47, 50, 23, 32, 8, 27]
  human_ids: [0, 1]

controller:
  # links: ["hip_base", "LL_foot", "RL_foot", "la_end_effector", "ra_end_effector", "neck_link2", "trunk_rz", "ra_link4", "la_link4"]  # must match the body part names 
  # points: [0, 0, 0, 0, 0, 0, 0, 0.11, 0.15, 0, 0]
  links: ["hip_base", "LL_foot", "RL_foot", "neck_link2", "trunk_rz", "la_end_effector", "ra_end_effector", "ra_link4", "la_link4"]  # must match the body part names 
  points: [0, 0, 0, 0.11, 0.15, 0, 0, 0, 0]